name = "QDash"
uuid = "83eaad3c-afcb-4ce2-befe-2408c0a99e9f"
authors = ["Tongyu Zhao"]
version = "0.1.0-DEV"

[deps]
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
