name = "QDash"
uuid = "83eaad3c-afcb-4ce2-befe-2408c0a99e9f"
authors = ["Tongyu Zhao"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
